services:
#    open_cephalon.example:
#        class: OpenCephalonBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    pre_persist.listener:
        class: OpenCephalonBundle\EventListener\PrePersistEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }

